### ISSUE TITLE
Portfolio MAE/MFE Chart

### ISSUE THREAD

**Issue by rossb34** [braverock/blotter#42]
The `chart.ME` function plots the MAE/MFE per symbol. In some cases, it is useful to analyze the MAE and MFE statistics at an aggregated portfolio level. I propose an option to chart the MAE/MFE for all symbols in a given portfolio, e.g. `Symbol = "all"`.

I see a few options for achieving this:

1. Loop over the symbols in the portfolio and `rbind` the output of `perTradeStats`.
2. Modify `perTradeStats` to accept an argument `Symbol = "all"` to return the trade statistics aggregated at the portfolio level.

**Comment by vi-to** [comment]
Hello. I have already a consistent solution to issue [#66](https://github.com/braverock/blotter/issues/66), but I am trying to see it in this light since it seems a useful feature. I can figure we want to allow for different dates/frequencies and so on, however I think this should be consistent across other measures as well. @braverock do you think a higher patch (to the object) an then some lower functions adjustments are more reasonable? Also, it would be useful to have some portfolio data ready for testing

**Comment by braverock** [comment]
@vi-to , I'm not sure I entirely understand what you are proposing.

I think #66 and pull request #77 for it look almost ready to merge, so I'll leave them out of scope for these remarks, and instead try to address what I think you may be talking about.

`chart.ME` is effectively a MAE/MFE visualization for the output of `perTradeStats`.  `perTradeStats` works by pairing up entry and exit transactions to construct "round turn trades".

I think from @rossb34 initial comment, that the loop approach is simplest.  My assumption is that a user would likely prefer to see the different portfolio constituents in different colors, and simply returning 'all' trades `rbind` ed together wouldn't really accomplish that.

In #43 @rossb34 suggested that either rbind or a list would be possible.  If we made it an option to `perTradeStats` and allowed for a `list` return type, the default would need to remain `rbind` so that we wouldn't break backwards compatibility.

It seems to me that this is probably the best way to go.  Change `perTradeStats` as in #43 to allow a vector of Symbols in the `Symbol` argument, and add an additional argument such as `combn.method=c('rbind','list')` which would default to `rbind`.  If you have a list return to `chart.ME`, add a legend and colors, if `rbind`, just chart them all together.  we could use symbols instead of colors to differentiate the different constrituents as well, replacing the up and down triangle symbols.

**Comment by vi-to** [comment]
I see your points and agree with you about how to best address this new feature, probably as @rossb34 suggested this is the easiest way too. In the beginning, I was thinking about adding (all) the portfolio aggregate values to the portfolio object, but indeed what you are suggesting seems better since it would allow selecting symbols subsets too. 
However, issues [#66](https://github.com/braverock/blotter/issues/66) as addressed by PR [#77](
https://github.com/braverock/blotter/pull/77) is giving me error
> Error in match.arg(x, c("bottomright", "bottom", "bottomleft", "left",  : 
  'arg' should be one of “bottomright”, “bottom”, “bottomleft”, “left”, “topleft”, “top”, “topright”, “right”, “center”
Called from: match.arg(x, c("bottomright", "bottom", "bottomleft", "left", 
    "topleft", "top", "topright", "right", "center"))

when tested on `data/amzn.rda`. I have a solution tested on same data and ready to PR.

**Comment by anshul96go** [comment]
@vi-to 
Please check now, I made a correction. Hope it works now.
